# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Dev

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci  # runs a clean npm install, removing any node_modules first
    - run: npm test -- --passWithNoTests
    - name: Archive node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Restore node_modules archive
      uses: actions/download-artifact@v3
      with:
        name: node_modules
    - uses: actions/checkout@v3
    - name: Build and merge to gh-pages
      run: npm run deploy

