# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Dev

on:
  workflow_dispatch:
    ref: 'refs/head/dev'
  workflow_run:
    workflows: [Test Dev]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'dev'
    - name: Use Node.js 14.19.1 (LTS 14) 
      uses: actions/setup-node@v3
      with:
        node-version: 14.19.1
        cache: 'npm'
    - name: Cache node_modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install node modules if not cached
      run: npm install
    - name: Configure git
      run: git config --global user.email "actions@github.com" && git config --global user.name "gh-pages action"
    - name: Build and merge to gh-pages
      run: NODE_DEBUG=gh-pages npm run deploy

